import { execFile } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { promisify } from 'node:util';
import type { JavaStatus, Settings } from '@lld/shared';
import { now } from '../db.js';

const pexec = promisify(execFile);

export const MAVEN_VERSION = '3.9.16';
export const WRAPPER_VERSION = '3.3.4';
export const JUNIT_VERSION = '5.14.4';

export interface MavenPaths {
  userHome: string;
  repository: string;
  settingsFile: string | null;
}

export function mavenPaths(dataRoot: string, settings: Settings): MavenPaths {
  if (!settings.java.useIsolatedMavenRepo) {
    const home = join(process.env.HOME ?? '', '.m2');
    return { userHome: home, repository: join(home, 'repository'), settingsFile: null };
  }
  // LLD_STUDIO_MAVEN_HOME lets several data folders (or the test suite) share one prepared cache.
  const userHome = process.env.LLD_STUDIO_MAVEN_HOME || join(dataRoot, 'maven');
  const repository = join(userHome, 'repository');
  const settingsFile = join(userHome, 'settings.xml');
  mkdirSync(userHome, { recursive: true });
  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by LLD Practice Studio: isolated local repository, no mirrors or credentials. -->\n<settings><localRepository>${escapeXml(repository)}</localRepository></settings>\n`;
  if (!existsSync(settingsFile) || readFileSync(settingsFile, 'utf8') !== xml) writeFileSync(settingsFile, xml);
  return { userHome, repository, settingsFile };
}

function escapeXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export function parseJavaVersion(output: string): { version: string; major: number } | null {
  const m = output.match(/version "([^"]+)"/);
  if (!m) return null;
  const v = m[1];
  const parts = v.split(/[._-]/);
  const major = parts[0] === '1' ? Number(parts[1]) : Number(parts[0]);
  return Number.isFinite(major) ? { version: v, major } : null;
}

/** Runs a short command and returns its output without throwing on nonzero exit. */
export async function runQuiet(cmd: string, args: string[], env: NodeJS.ProcessEnv = { PATH: '/usr/bin:/bin' }): Promise<{ code: number; stdout: string; stderr: string }> {
  try {
    const { stdout, stderr } = await pexec(cmd, args, { timeout: 15000, env, maxBuffer: 1024 * 1024 });
    return { code: 0, stdout, stderr };
  } catch (e) {
    const err = e as { code?: number | string; stdout?: string; stderr?: string };
    return { code: typeof err.code === 'number' ? err.code : -1, stdout: err.stdout ?? '', stderr: err.stderr ?? String(e) };
  }
}

async function probeHome(home: string): Promise<{ home: string; version: string; major: number; javac: boolean } | null> {
  const java = join(home, 'bin', 'java');
  if (!existsSync(java)) return null;
  const { stdout, stderr } = await runQuiet(java, ['-version']);
  const parsed = parseJavaVersion(stderr + stdout);
  if (!parsed) return null;
  return { home, ...parsed, javac: existsSync(join(home, 'bin', 'javac')) };
}

async function candidateHomes(): Promise<{ home: string; source: string }[]> {
  const out: { home: string; source: string }[] = [];
  if (process.env.JAVA_HOME) out.push({ home: process.env.JAVA_HOME, source: 'JAVA_HOME' });
  if (process.platform === 'darwin' && existsSync('/usr/libexec/java_home')) {
    // `java_home -V` lists every installed JDK on stderr.
    const { stdout, stderr } = await runQuiet('/usr/libexec/java_home', ['-V']);
    for (const line of `${stdout}\n${stderr}`.split('\n')) {
      const m = line.match(/\s(\/\S.*\/Contents\/Home)\s*$/);
      if (m) out.push({ home: m[1], source: 'java_home' });
    }
  }
  for (const base of ['/opt/homebrew/opt', '/usr/local/opt']) {
    if (!existsSync(base)) continue;
    for (const name of readdirSync(base)) {
      if (!name.startsWith('openjdk')) continue;
      const home = join(base, name, 'libexec', 'openjdk.jdk', 'Contents', 'Home');
      if (existsSync(home)) out.push({ home, source: 'homebrew' });
    }
  }
  for (const base of ['/usr/lib/jvm']) {
    if (!existsSync(base)) continue;
    for (const name of readdirSync(base)) out.push({ home: join(base, name), source: 'system' });
  }
  const seen = new Set<string>();
  return out.filter((c) => (seen.has(c.home) ? false : (seen.add(c.home), true)));
}

/**
 * Finds a JDK that can compile for the configured release. Preference order:
 * explicit setting → JAVA_HOME → newest suitable installed JDK.
 */
export async function detectJava(settings: Settings, dataRoot: string): Promise<JavaStatus> {
  const release = settings.java.release;
  const maven = mavenPaths(dataRoot, settings);
  const mavenInfo = {
    wrapperVersion: WRAPPER_VERSION,
    mavenVersion: MAVEN_VERSION,
    distributionCached: isDistributionCached(maven.userHome),
    dependenciesCached: existsSync(join(maven.repository, 'org', 'junit', 'jupiter', 'junit-jupiter-engine', JUNIT_VERSION)) &&
      existsSync(join(maven.repository, 'org', 'apache', 'maven', 'surefire', 'surefire-junit-platform')),
    userHome: maven.userHome,
    repository: maven.repository,
  };
  const base = { release, maven: mavenInfo, checkedAt: now() };

  const probed: { home: string; version: string; major: number; javac: boolean; source: string }[] = [];
  if (settings.java.javaHome) {
    const p = await probeHome(settings.java.javaHome);
    if (!p) {
      return {
        ...base,
        ok: false,
        javaHome: settings.java.javaHome,
        javaVersion: null,
        javaMajor: null,
        javacFound: false,
        meetsRelease: false,
        source: 'settings',
        candidates: [],
        detail: `The configured Java home (${settings.java.javaHome}) does not contain a working bin/java.`,
      };
    }
    probed.push({ ...p, source: 'settings' });
  } else {
    for (const c of await candidateHomes()) {
      const p = await probeHome(c.home);
      if (p) probed.push({ ...p, source: c.source });
    }
  }
  const suitable = probed.filter((p) => p.javac && p.major >= release);
  const chosen = settings.java.javaHome
    ? probed[0]
    : (suitable.find((p) => p.source === 'JAVA_HOME') ?? suitable.sort((a, b) => b.major - a.major)[0] ?? probed[0]);
  const candidates = probed.map((p) => ({ home: p.home, version: p.version, major: p.major }));
  if (!chosen) {
    return {
      ...base,
      ok: false,
      javaHome: null,
      javaVersion: null,
      javaMajor: null,
      javacFound: false,
      meetsRelease: false,
      source: null,
      candidates,
      detail: `No JDK found. Install JDK ${release} or newer (for example: brew install openjdk@21) or set the Java home in Settings.`,
    };
  }
  const meets = chosen.major >= release;
  const ok = meets && chosen.javac;
  return {
    ...base,
    ok,
    javaHome: chosen.home,
    javaVersion: chosen.version,
    javaMajor: chosen.major,
    javacFound: chosen.javac,
    meetsRelease: meets,
    source: chosen.source,
    candidates,
    detail: !chosen.javac
      ? `${chosen.home} is a JRE without javac; a full JDK is required.`
      : !meets
        ? `Java ${chosen.version} cannot compile for release ${release}. Install JDK ${release}+ or lower the target in Settings.`
        : !mavenInfo.distributionCached || !mavenInfo.dependenciesCached
          ? 'JDK ready. Maven and JUnit have not been downloaded yet — run "Prepare toolchain" once (needs internet, ~25 MB).'
          : `JDK ${chosen.version} ready; Maven ${MAVEN_VERSION} and JUnit ${JUNIT_VERSION} are cached for offline builds.`,
  };
}

function isDistributionCached(userHome: string): boolean {
  const dir = join(userHome, 'wrapper', 'dists', `apache-maven-${MAVEN_VERSION}`);
  if (!existsSync(dir)) return false;
  return readdirSync(dir).some((h) => existsSync(join(dir, h, 'bin', 'mvn')));
}
